### ISSUE TITLE
[Bug]: hash no longer in 1.27.0 of deo

### ISSUE THREAD

**Issue by ralyodio** [halvardssm/deno-nessie#164]
### Operating System

Linux Ubuntu 20.04

### Deno version

1.27.0

### Nessie version

latest

### Bug description

Getting this error:

```
Found latest version 1.27.0
Checking https://github.com/denoland/deno/releases/download/v1.27.0/deno-x86_64-unknown-linux-gnu.zip
36.1 MiB / 36.1 MiB (100.0%)
Deno is upgrading to version 1.27.0
Archive:  /tmp/.tmpAT10T4/deno.zip
  inflating: deno                    
Upgraded successfully
Download ⠸ https://deno.land/std/hash/mod.ts                                                                                                                              Warning Implicitly using latest version (0.161.0) for https://deno.land/std/hash/mod.ts
TypeError: Module not found "https://deno.land/std/hash/mod.ts".
    at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:28
    at async Function.init (https://deno.land/x/nessie@2.0.10/cli/state.ts:80:23)
    at async Command.migrate [as fn] (https://deno.land/x/nessie@2.0.10/cli/commands.ts:136:17)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.2/command/command.ts:1463:7)
    at async cli (https://deno.land/x/nessie@2.0.10/cli.ts:29:3)
    at async run (https://deno.land/x/nessie@2.0.10/cli.ts:139:5)
    at async https://deno.land/x/nessie@2.0.10/cli.ts:158:1 
```

Trying to run migrations.

### Steps to reproduce

vFound latest version 1.27.0
Checking https://github.com/denoland/deno/releases/download/v1.27.0/deno-x86_64-unknown-linux-gnu.zip
36.1 MiB / 36.1 MiB (100.0%)
Deno is upgrading to version 1.27.0
Archive:  /tmp/.tmpAT10T4/deno.zip
  inflating: deno                    
Upgraded successfully
Download ⠸ https://deno.land/std/hash/mod.ts                                                                                                                              Warning Implicitly using latest version (0.161.0) for https://deno.land/std/hash/mod.ts
TypeError: Module not found "https://deno.land/std/hash/mod.ts".
    at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:28
    at async Function.init (https://deno.land/x/nessie@2.0.10/cli/state.ts:80:23)
    at async Command.migrate [as fn] (https://deno.land/x/nessie@2.0.10/cli/commands.ts:136:17)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.2/command/command.ts:1463:7)
    at async cli (https://deno.land/x/nessie@2.0.10/cli.ts:29:3)
    at async run (https://deno.land/x/nessie@2.0.10/cli.ts:139:5)
    at async https://deno.land/x/nessie@2.0.10/cli.ts:158:1

**Comment by ralyodio** [comment]
I think you're relying on a super old version of god cryto

**Comment by anishkny** [comment]
I was seeing something similar locally which turned out because I was importing an old version `nessie@2.0.0`. Once I upgraded to `nessie@2.0.10`, it worked fine.

I am curious, what does your migration file look like?

**Comment by ralyodio** [comment]
v2.0.10 works now. Thanks
