### ISSUE TITLE
[Bug]: god crypto error

### ISSUE THREAD

**Issue by ralyodio** [halvardssm/deno-nessie#166]
### Operating System

linux

### Deno version

deno 1.32.3

### Nessie version

2.0.10

### Bug description

Warning Implicitly using latest version (0.190.0) for https://deno.land/std/hash/mod.ts
Download https://deno.land/std@0.190.0/hash/mod.ts
TypeError: Module not found "https://deno.land/std/hash/mod.ts".
    at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:28
    at async Function.init (https://deno.land/x/nessie@2.0.10/cli/state.ts:80:23)
    at async Command.migrate [as fn] (https://deno.land/x/nessie@2.0.10/cli/commands.ts:136:17)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.2/command/command.ts:1463:7)
    at async cli (https://deno.land/x/nessie@2.0.10/cli.ts:29:3)
    at async run (https://deno.land/x/nessie@2.0.10/cli.ts:139:5)
    at async https://deno.land/x/nessie@2.0.10/cli.ts:158:1 
 This error is most likely unrelated to Nessie, and is probably related to the client, the connection config or the query you are trying to execute.

### Steps to reproduce

Warning Implicitly using latest version (0.190.0) for https://deno.land/std/hash/mod.ts
Download https://deno.land/std@0.190.0/hash/mod.ts
TypeError: Module not found "https://deno.land/std/hash/mod.ts".
    at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:28
    at async Function.init (https://deno.land/x/nessie@2.0.10/cli/state.ts:80:23)
    at async Command.migrate [as fn] (https://deno.land/x/nessie@2.0.10/cli/commands.ts:136:17)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.2/command/command.ts:1463:7)
    at async cli (https://deno.land/x/nessie@2.0.10/cli.ts:29:3)
    at async run (https://deno.land/x/nessie@2.0.10/cli.ts:139:5)
    at async https://deno.land/x/nessie@2.0.10/cli.ts:158:1 
 This error is most likely unrelated to Nessie, and is probably related to the client, the connection config or the query you are trying to execute.

### Aditional information

Warning Implicitly using latest version (0.190.0) for https://deno.land/std/hash/mod.ts
Download https://deno.land/std@0.190.0/hash/mod.ts
TypeError: Module not found "https://deno.land/std/hash/mod.ts".
    at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:28
    at async Function.init (https://deno.land/x/nessie@2.0.10/cli/state.ts:80:23)
    at async Command.migrate [as fn] (https://deno.land/x/nessie@2.0.10/cli/commands.ts:136:17)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.2/command/command.ts:1463:7)
    at async cli (https://deno.land/x/nessie@2.0.10/cli.ts:29:3)
    at async run (https://deno.land/x/nessie@2.0.10/cli.ts:139:5)
    at async https://deno.land/x/nessie@2.0.10/cli.ts:158:1 
 This error is most likely unrelated to Nessie, and is probably related to the client, the connection config or the query you are trying to execute.

**Comment by ralyodio** [comment]
yeah deno and this project are pretty mcuh dead

**Comment by halvardssm** [comment]
Quite busy these days. Feel free to open a PR and I'll review it.

**Comment by halvardssm** [comment]
I'm closing this issue as it is inactive
