### ISSUE TITLE
[Bug]: TypeError: Module not found "https://deno.land/std/hash/mod.ts".

### ISSUE THREAD

**Issue by ralyodio** [halvardssm/deno-nessie#169]
### Operating System

arch

### Deno version

1.38

### Nessie version

2.0.11

### Bug description

Warning Implicitly using latest version (0.205.0) for https://deno.land/std/hash/mod.ts
TypeError: Module not found "https://deno.land/std/hash/mod.ts".
at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:28
at async ClientSQLite._migrationHandler (https://deno.land/x/nessie@2.0.11/clients/AbstractClient.ts:246:37)
at async ClientSQLite._migrate (https://deno.land/x/nessie@2.0.11/clients/AbstractClient.ts:103:7)
at async ClientSQLite.migrate (https://deno.land/x/nessie@2.0.11/clients/ClientSQLite.ts:107:5)
at async Command.migrate [as fn] (https://deno.land/x/nessie@2.0.11/cli/commands.ts:138:3)
at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
at async cli (https://deno.land/x/nessie@2.0.11/cli.ts:29:3)
at async run (https://deno.land/x/nessie@2.0.11/cli.ts:139:5)
at async https://deno.land/x/nessie@2.0.11/cli.ts:158:1 {
code: "ERR_MODULE_NOT_FOUND"
}

### Steps to reproduce

Warning Implicitly using latest version (0.205.0) for https://deno.land/std/hash/mod.ts
TypeError: Module not found "https://deno.land/std/hash/mod.ts".
at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:28
at async ClientSQLite._migrationHandler (https://deno.land/x/nessie@2.0.11/clients/AbstractClient.ts:246:37)
at async ClientSQLite._migrate (https://deno.land/x/nessie@2.0.11/clients/AbstractClient.ts:103:7)
at async ClientSQLite.migrate (https://deno.land/x/nessie@2.0.11/clients/ClientSQLite.ts:107:5)
at async Command.migrate [as fn] (https://deno.land/x/nessie@2.0.11/cli/commands.ts:138:3)
at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
at async cli (https://deno.land/x/nessie@2.0.11/cli.ts:29:3)
at async run (https://deno.land/x/nessie@2.0.11/cli.ts:139:5)
at async https://deno.land/x/nessie@2.0.11/cli.ts:158:1 {
code: "ERR_MODULE_NOT_FOUND"
}

**Comment by ralyodio** [comment]
this has been replaced with `std/crypto`

**Comment by halvardssm** [comment]
Hi @ralyodio I did an inspection of the dependencies, but I could not see any usage of `https://deno.land/std/hash/mod.ts` (unversioned). Are you sure that your migration files and the config file is using the latest nessie version?

**Comment by ralyodio** [comment]
It's from god crypto which Nessie requires.

**Comment by halvardssm** [comment]
@ralyodio When doing deno info, there is no usage of god crypto. I know it was from a previous version of sqlite and MySQL, but in recent versions this was removed. Have you double checked that you have update nessie in the migration files, the config file, and the cli? try to run with `-r`, and let me know if you still have the issue.

```
deno info -r https://raw.githubusercontent.com/halvardssm/deno-nessie/main/mod.ts
deno info -r https://raw.githubusercontent.com/halvardssm/deno-nessie/main/cli.ts
```

**Comment by ralyodio** [comment]
sorry, I'm not sure what you're asking me. I ran those outputs and got a long list of a tree of urls to github.

**Comment by halvardssm** [comment]
No worries, I am asking you if you are sure that you have all nessie imports updated to latest?

Can you maybe share a repo with me so that I can take a look and debug myself?

**Comment by ralyodio** [comment]
https://github.com/avenasea/avenasea-api

**Comment by halvardssm** [comment]
I can see from your [config file](https://github.com/avenasea/avenasea-api/blob/main/nessie.config.ts#L4) that you are using an outdated nessie version. 

Also, although I generally advise against it, I also see that the migration files are using old nessie imports, if updating the config file doesn't solve it, you can try to update the migration files as well, but make sure to backup the database beforehand.
