### ISSUE TITLE
Cli Command not working.

### ISSUE THREAD

**Issue by bander-saeed94** [halvardssm/deno-nessie#38]
Cli not working.

Running rollback or migrate shows this error:

```
$ deno run --allow-net --allow-read https://deno.land/x/nessie/cli.ts rollback all
```
```
Compile https://deno.land/x/nessie/cli.ts
error: TS2339 [ERROR]: Property 'initClient' does not exist on type 'State'.
      await state.initClient();
                  ~~~~~~~~~~
    at https://deno.land/x/nessie/cli.ts:49:19

TS2554 [ERROR]: Expected 1 arguments, but got 0.
        await state.client!.migrate();
                            ~~~~~~~~~
    at https://deno.land/x/nessie/cli.ts:52:29

    An argument for 'amount' was not provided.
      migrate: (amount: amountMigrateT) => Promise<void>;
                ~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/nessie/clients/AbstractClient.ts:15:13

TS2554 [ERROR]: Expected 1 arguments, but got 0.
        await state.client!.rollback();
                            ~~~~~~~~~~
    at https://deno.land/x/nessie/cli.ts:54:29

    An argument for 'amount' was not provided.
      rollback: (amount: amountRollbackT) => Promise<void>;
                 ~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/nessie/clients/AbstractClient.ts:16:14

Found 3 errors.
```

**Comment by halvardssm** [comment]
Hi @bander-saeed94 ! Have you tried with adding the `-r` flag? v0.5 has a lot of breaking changes, and these errors look like some version missmatch.

**Comment by bander-saeed94** [comment]
Yes. I also had to update nessie.config.ts file.
