### ISSUE TITLE
[QUESTION] Facing problems with connections - github actions

### ISSUE THREAD

**Issue by Leonardo-Rocha** [halvardssm/deno-nessie#57]
Hey @halvardssm , I'm using using nessie with local containers and they're working great. However, when I tried to use it in github actions, nessie won't connect (using postgres), it gives me the following error:

```
PostgresError: password authentication failed for user "root"
    at parseError (https://deno.land/x/postgres@v0.4.1/error.ts:105:10)
    at Connection._readAuthResponse (https://deno.land/x/postgres@v0.4.1/connection.ts:199:13)
    at async Connection.handleAuth (https://deno.land/x/postgres@v0.4.1/connection.ts:188:9)
    at async Connection.startup (https://deno.land/x/postgres@v0.4.1/connection.ts:150:5)
    at async Client.connect (https://deno.land/x/postgres@v0.4.1/client.ts:14:5)
    at async ClientPostgreSQL.prepare (https://deno.land/x/nessie/clients/ClientPostgreSQL.ts:34:5)
    at async run (https://deno.land/x/nessie/cli.ts:71:9)
##[error]Process completed with exit code 1.
```
Have you already faced this error? Can you help me?
Here are the files:
[nessie.config.ts](https://github.com/Knights-of-Tupan/dungeons-and-denos/blob/master/src/database/nessie.config.ts)
[.env.test](https://github.com/Knights-of-Tupan/dungeons-and-denos/blob/master/.env.test)
[ci.yml](https://github.com/Knights-of-Tupan/dungeons-and-denos/blob/master/.github/workflows/ci.yml)

**Comment by halvardssm** [comment]
Hi @Leonardo-Rocha ! Your hostname should probably be localhost. Let me know if this solves it for you 💪

**Comment by Leonardo-Rocha** [comment]
It didn't work, same error :(

**Comment by halvardssm** [comment]
hm, try to run it with the -d flag, it should give some debugging output and make it easier for you to see where things are going wrong. Let me know when you have updated with this so that I can take a look 🤔

**Comment by halvardssm** [comment]
I assume this issue has been taken care of, and that this is no longer a problem so I will close this issue 😄
