### ISSUE TITLE
[BUG] CLI migrate command not working

### ISSUE THREAD

**Issue by narwy** [halvardssm/deno-nessie#72]
Latest everything on windows:

`docker exec -it api deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts migrate`

```
Check https://deno.land/x/nessie@v1.0.2/cli.ts
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.55.0/path/win32.ts:917:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.55.0/path/posix.ts:438:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

Found 4 errors.
```

**Comment by narwy** [comment]
Just realised it's not pulling v1.0.4 from the deno.land/x

@halvardssm you need to add the module again to deno.land/x and setup the github webhook and do another tag / release for it to appear up

**Comment by halvardssm** [comment]
Yeah, just realized that I missed the notification about this. It should be added now 👍
