### ISSUE TITLE
[BUG] nessie.config.ts migrationFolder and seedFolder paths not taking effect

### ISSUE THREAD

**Issue by gaylonalfano** [halvardssm/deno-nessie#82]
**System (please complete the following information):**
 - OS: Mac OS Catalina
 - Deno version 1.4.2
 - Nessie version 1.1.2

**Describe the bug**
When I initialize Nessie running the standard command: `deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts init`, it creates a `project/db` directory inside my current working directory (`project`), as well as the default `nessie.config.ts` file (`project/nessie.config.ts`). That seems standard and no issue there.

However, if I want to store my migrations and seeds into a different directory/path structure by changing the `migrationFolder` and `seedFolder` paths, it does not seem to work. 

Here is my current `project/nessie.config.ts` config:
```
import { ClientOptions, ClientPostgreSQL, ConnectionOptions } from "./deps.ts";
import config from "./src/app/config/config.ts";

/** These are the default config options. */
const nessieOptions: ClientOptions = {
  migrationFolder: "./src/app/db/migrations",
  seedFolder: "./src/app/db/seeds",
  experimental: true,
};

// Official example imports deno-postgres ConnectionOptions
// https://github.com/halvardssm/deno-nessie/blob/master/examples/config-postgres.ts
const connectionConfig: ConnectionOptions = {
  database: config.DB_DATABASE,
  hostname: config.DB_HOST,
  port: +config.DB_PORT,
  user: config.DB_USER,
  password: config.DB_PASSWORD,
};

export default {
  nessiePostgresClient: new ClientPostgreSQL(nessieOptions, connectionConfig),
};

```

**To Reproduce**

1. For example, I can change the default `migrationFolder: "./db/migrations"` to, say, `migrationFolder: "./src/app/db/migrations"` and `seedFolder: "./src/app/db/seeds"`. 

2. I save my changes in `nessie.config.ts` and then, **_inside my project root folder_**,  I run my first `make [name]` command to create my first migration: `deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts make create_users`. After this command runs, I still end up with a `project/db/migrations/12345_create_users.ts` file, instead of my preferred and configured path of `project/src/app/db/migrations/12345_create_users.ts`.

3. **It's only when I run the Nessie command from my `project/src/app` directory, does Nessie create the nested `project/src/app/db/migrations` and `project/src/app/db/seeds` directories.** 

**Expected behavior**
My expectation is that my nessie configuration will create my nested directories and store the new migration file inside `project/src/app/db/migrations/11111_create_users.ts`. However, it instead saves the migration file inside `project/db/migrations/11111_create_users.ts`. I have even deleted the default `./db` directory (created when I first ran `init` with Nessie) and re-ran the `make [name]` to create another migration. It still doesn't seem to use the paths specified in my `nessie.config.ts` file.

Perhaps I'm missing something. I just assumed that my `nessie.config.ts` config would store my migration files and seed files in the relative paths I specify for `migrationsFolder` and `seedFolder`, but perhaps I'm missing something. For now, I just make sure I am in my `project/src/app` directory before I run any Nessie commands. Please let me know if I can provide anything else.

**Comment by gaylonalfano** [comment]
Okay, I may have resolved the directory issue by using the `--reload` flag. I'm still trying it out but it seems like I can now run my Nessie commands and the custom paths I configure for migrations and seeds are working. I'll test a bit more and then close.

I now am running into a 
```
import { AbstractMigration, Info } from "https://deno.land/x/nessie/mod.ts"; // import Dex from "https://deno.land/x/dex/mod.ts"; export default class ExperimentalMigration extends AbstractMigration { /** Runs on migrate */ async up(info: Info): Promise<void> { this.client.query("CREATE TABLE table1 (id int)"); } /** Runs on rollback */ async down(info: Info): Promise<void> { this.client.query("DROP TABLE table1"); } }
```

Here's the output from the `migrate` command with the `TypeError: MigrationClass is not a constructor`:
```
❯ deno-vue-postgres-starter/backend add-nessie [!?] deno run --allow-net --allow-read --allow-write https://deno.land/x/nessie/cli.ts migrate -d
State:
[
  true,
  "file:///Users/gaylonalfano/Code/deno-vue-postgres-starter/backend/nessie.config.ts"
]
Checking config path
Amount pre:
undefined
Latest migrations:
undefined
Filtered and sorted migration files:
[ "1602682202673-create_users.ts" ]
Check file:///Users/gaylonalfano/Code/deno-vue-postgres-starter/backend/src/app/db/migrations/1602682202673-create_users.ts
TypeError: MigrationClass is not a constructor
    at ClientPostgreSQL._migrationHandler (AbstractClient.ts:215:25)
    at async ClientPostgreSQL.migrate (AbstractClient.ts:97:9)
    at async ClientPostgreSQL.migrate (ClientPostgreSQL.ts:73:5)
    at async run (https://deno.land/x/nessie@v1.1.2/cli.ts:74:11)
```

Still investigating but I'll keep you posted. I believe the `--reload` flag was a step in the right direction. Lots to learn!
